"use client";
import { useState, useEffect } from "react";
import { purchaseQuote } from "@/lib/commerce";
import { ArrowUpRight, ArrowRight, Gem, MapPin, CalendarDays, Sparkles, Check, X } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
const collection = [
 {id:"celeste",name:"Céleste",category:"Necklaces",rent:350,buy:8500,position:"50% 55%",description:"A diamond necklace for the moment all eyes turn to you."},
 {id:"etoile",name:"Étoile",category:"Earrings",rent:180,buy:4200,position:"20% 45%",description:"Diamond earrings that catch the light with every turn."},
 {id:"lumiere",name:"Lumière",category:"Bracelets",rent:220,buy:5600,position:"75% 65%",description:"A delicate line of diamonds to complete your wedding look."},
 {id:"aureole",name:"Auréole",category:"Tiaras",rent:450,buy:10000,position:"50% 20%",description:"A diamond tiara for an unforgettable entrance."},
];
const eur=(n:number)=>new Intl.NumberFormat("en-IE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);
const day=(s:string)=>Date.parse(s+"T00:00:00Z");
export default function Home(){
 const [category,setCategory]=useState("All diamonds"),[piece,setPiece]=useState<typeof collection[number]|null>(null),[start,setStart]=useState(""),[end,setEnd]=useState(""),[step,setStep]=useState(0),[showrooms,setShowrooms]=useState(false),[price,setPrice]=useState(5000),[voucher,setVoucher]=useState(300),[early,setEarly]=useState(true),[error,setError]=useState("");
 const days=start&&end?Math.round((day(end)-day(start))/86400000):0;
 const today=new Date();const minDate=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}-${String(today.getDate()).padStart(2,"0")}`;
 const valid=days>=4&&days<=365&&start>=minDate;
 const rental=piece?Math.round(piece.rent*Math.max(4,days)/4):0;
 const total=purchaseQuote(Math.round(price*100),Math.round(voucher*100),early).totalCents/100;
 useEffect(()=>{
  type ToolContext={registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>};
  const context=(document as Document & {modelContext?:ToolContext}).modelContext;
  if(!context)return;
  const lifecycle=new AbortController();
  Promise.resolve(context.registerTool({name:"calculate_purchase_benefit",description:"Calculate an illustrative diamond purchase with a rental voucher and optional early purchase discount. Does not place an order or validate a real voucher.",inputSchema:{type:"object",properties:{fullPriceCents:{type:"integer",minimum:0},voucherCents:{type:"integer",minimum:0},withinThreeMonths:{type:"boolean"}},required:["fullPriceCents","voucherCents","withinThreeMonths"],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{const v=input as Record<string,unknown>;if(!v||typeof v.withinThreeMonths!=="boolean")throw new Error("Invalid input");return purchaseQuote(v.fullPriceCents as number,v.voucherCents as number,v.withinThreeMonths);}}, {signal:lifecycle.signal})).catch(()=>{});
  return ()=>lifecycle.abort();
 },[]);
 function choose(p:typeof collection[number]){setPiece(p);setStart("");setEnd("");setStep(0);setError("")}
 return <main>
  <div className="topline">A moment to shine. A little sparkle to keep.</div>
  <header><a className="wordmark" href="#">VALTIER<span>JEWELERY</span></a><nav aria-label="Main navigation"><a href="#collection">THE DIAMONDS</a><a href="#how-it-works">HOW IT WORKS</a><a href="#your-voucher">YOUR VOUCHER</a></nav><button className="showroom-link" onClick={()=>setShowrooms(true)}><MapPin size={16}/> VISIT A SHOWROOM</button></header>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">SOMETHING BORROWED. SOMETHING BRILLIANT.</p><h1>Shine like a star<br/>on your <em>wedding day.</em></h1><p className="hero-description"> Wear extraordinary diamonds, for a small fraction of the price.<br/>Rent for your celebration. Treasure the memory.</p><a className="primary" href="#collection">DISCOVER THE DIAMONDS <ArrowUpRight size={18}/></a><div className="hero-facts"><span>4-day minimum rental</span><span>Rental value back as a voucher</span></div></div></section>
  <section id="collection" className="collection"><div className="section-heading"><div><p className="eyebrow">FOR YOUR ONCE-IN-A-LIFETIME</p><h2>Find your kind of <em>brilliant.</em></h2></div><p>For the bride. For the celebration.<br/>For a moment that is entirely yours.</p></div><div className="filters">{["All diamonds","Necklaces","Earrings","Bracelets","Tiaras"].map(c=><button key={c} aria-pressed={c===category} onClick={()=>setCategory(c)}>{c}</button>)}<span>{collection.filter(p=>category==="All diamonds"||p.category===category).length} pieces</span></div><div className="product-grid">{collection.filter(p=>category==="All diamonds"||p.category===category).map((p,i)=><article key={p.id}><button className="product-photo" onClick={()=>choose(p)} aria-label={`Explore ${p.name} ${p.category.toLowerCase()}`}><img src="/diamonds.png" alt="Illustrative bridal diamond collection" style={{objectPosition:p.position}}/><span className="product-category">{p.category}</span><span className="product-arrow"><ArrowUpRight size={19}/></span></button><div className="product-title"><h3>{p.name}</h3><span>0{collection.indexOf(p)+1}</span></div><p className="product-description">Diamond {p.category.toLowerCase().replace(/s$/,"")}</p><div className="product-price"><span><strong>{eur(p.rent)}</strong> / 4 days</span><button onClick={()=>choose(p)}>Explore <ArrowRight size={15}/></button></div></article>)}</div><p className="preview-note">Sample collection and pricing · Jewelry images are illustrative. Real pieces and availability will be added before bookings open.</p></section>
  <section id="how-it-works" className="journey"><div><p className="eyebrow">EFFORTLESS, FROM YES TO I DO</p><h2>Your day.<br/><em>Your diamonds.</em></h2><button className="text-link" onClick={()=>setShowrooms(true)}>Prefer to try them on? <ArrowUpRight size={17}/></button></div><div className="journey-steps"><article><span>01</span><div><h3>Find your sparkle</h3><p>Explore diamond earrings, necklaces, bracelets and tiaras. Try your favourites in selected showrooms.</p></div></article><article><span>02</span><div><h3>Make the moment yours</h3><p>Choose your dates and rent for at least four days, with time to enjoy your celebration.</p></div></article><article><span>03</span><div><h3>Let the sparkle stay</h3><p> Once you return your jewelry, the feeling stays forever. Your memory and the pictures will remind you the shine you had the most important day of your life. </p></div></article></div></section>
  <section id="your-voucher" className="voucher-section"><div className="voucher-copy"><p className="eyebrow">YOUR NEXT CHAPTER, IN DIAMONDS</p><h2>A wedding day rental.<br/><em>A gift to your future.</em></h2><p>Your rental fee becomes a purchase voucher valid for <strong>three years</strong>.</p><p>Buy within the first <strong>three months</strong> and enjoy an extra <strong>10% off the full price</strong> too. We apply the discount first, then your voucher.</p><span className="voucher-detail"><Sparkles size={18}/> The two benefits add up.</span></div><div className="calculator"><p className="eyebrow">SEE HOW YOUR VOUCHER WORKS</p><div className="calculator-inputs"><label>Jewelry price (€)<input type="number" min="0" max="1000000" value={price} onChange={e=>setPrice(Math.max(0,Math.min(1000000,Number(e.target.value))))}/></label><label>Rental voucher (€)<input type="number" min="0" max="1000000" value={voucher} onChange={e=>setVoucher(Math.max(0,Math.min(1000000,Number(e.target.value))))}/></label></div><label className="check-label"><input type="checkbox" checked={early} onChange={e=>setEarly(e.target.checked)}/> Purchasing within the first 3 months</label><dl><div><dt>Full purchase price</dt><dd>{eur(price)}</dd></div>{early&&<div><dt>Early purchase discount · 10%</dt><dd>−{eur(price*.1)}</dd></div>}<div><dt>Your rental voucher</dt><dd>−{eur(Math.min(voucher,price*(early?.9:1)))}</dd></div><div className="calculator-total"><dt>You pay</dt><dd>{eur(total)}</dd></div></dl><p>Illustrative calculation. Voucher eligibility is verified at purchase.</p></div></section>
  <section className="showroom-section"><MapPin size={28}/><p className="eyebrow">FALL IN LOVE IN PERSON</p><h2>Some things deserve<br/><em>to be tried on.</em></h2><p>Discover how your favourite diamonds feel in selected showrooms.</p><button className="primary" onClick={()=>setShowrooms(true)}>Explore showroom visits <ArrowUpRight size={18}/></button></section>
  <footer><a className="wordmark" href="#">VALTIER<span>JEWELERY</span></a><p>Something borrowed. Unforgettably yours.</p><span>© {new Date().getFullYear()} Valtier Jewelery · EUR €</span></footer>
  <Dialog open={!!piece} onOpenChange={v=>{if(!v)setPiece(null)}}><DialogContent className="booking-dialog">{piece&&<><div className="booking-photo"><img src="/diamonds.png" alt="Illustrative bridal diamonds"/><span>VALTIER / {piece.category.toUpperCase()}</span></div><div className="booking-content"><p className="eyebrow">{step===0?"YOUR SOMETHING BORROWED":"YOUR RENTAL SUMMARY"}</p><DialogTitle className="booking-title">{piece.name}</DialogTitle><DialogDescription>{piece.description}</DialogDescription>{step===0?<><div className="dates"><label>Rental starts<input type="date" min={minDate} value={start} onChange={e=>setStart(e.target.value)}/></label><label>Return date<input type="date" min={start?new Date(day(start)+4*86400000).toISOString().slice(0,10):minDate} value={end} onChange={e=>setEnd(e.target.value)}/></label></div><p className="field-help">Minimum 4 days. The return date is not counted as a rental day.</p>{start&&end&&!valid&&<p className="error" role="alert">Choose a current or future start date and a rental between 4 and 365 days.</p>}<div className="rental-total"><span>{valid?`${days}-day rental`:"4-day rental from"}</span><strong>{eur(rental)}</strong></div><p className="voucher-callout"><Gem size={18}/> Receive a {eur(rental)} purchase voucher, valid for 3 years.</p><p className="field-help">Sample pricing: {eur(piece.rent)} for 4 days, then {eur(piece.rent/4)} per additional day. Final delivery and deposit terms are pending.</p><button className="primary" disabled={!valid} onClick={()=>setStep(1)}>Continue to checkout <ArrowRight size={18}/></button></>:<><div className="summary-lines"><p><span>Rental dates</span><strong>{start} → {end}</strong></p><p><span>Duration</span><strong>{days} days</strong></p><p><span>Rental subtotal</span><strong>{eur(rental)}</strong></p><p><span>Purchase voucher earned</span><strong>{eur(rental)}</strong></p></div><div className="checkout-status"><CalendarDays size={21}/><div><strong>Online bookings are opening soon</strong><p>Payment is not connected yet. Your selection has not been reserved and no payment will be taken.</p></div></div><button className="primary" disabled>Payment coming soon</button><button className="text-link" onClick={()=>setStep(0)}>Back to rental dates</button></>}</div></>}</DialogContent></Dialog>
  <Dialog open={showrooms} onOpenChange={setShowrooms}><DialogContent className="showroom-dialog"><MapPin size={30}/><DialogTitle>Meet your wedding-day diamonds.</DialogTitle><DialogDescription>Try on your favourite pieces in selected showrooms before choosing your rental.</DialogDescription><div className="checkout-status"><p>Showroom locations and appointment booking will be available here soon.</p></div><p className="field-help">No appointment has been booked.</p></DialogContent></Dialog>
 </main>
}

